"""Them cot points_discount vao orders

Revision ID: 044cf1e95198
Revises: 6d1265f52ad5
Create Date: 2025-12-07 07:32:01.715006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044cf1e95198'
down_revision: Union[str, Sequence[str], None] = '6d1265f52ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('points_discount', sa.Numeric(precision=12, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'points_discount')
    # ### end Alembic commands ###
