"""Nang cap User CRM va Table Status

Revision ID: 6d1265f52ad5
Revises: c82c9397c984
Create Date: 2025-12-04 09:24:33.048117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d1265f52ad5'
down_revision: Union[str, Sequence[str], None] = 'c82c9397c984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('TRONG', 'CO_KHACH', 'DAT_TRUOC', name='tablestatus'),
               existing_nullable=True)
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('total_spent', sa.Numeric(precision=12, scale=0), nullable=True))
    op.add_column('users', sa.Column('order_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('internal_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'internal_note')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'order_count')
    op.drop_column('users', 'total_spent')
    op.drop_column('users', 'last_order_date')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    op.alter_column('tables', 'status',
               existing_type=sa.Enum('TRONG', 'CO_KHACH', 'DAT_TRUOC', name='tablestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
